#!/bin/sh

while read local_ref local_sha remote_ref remote_sha
do
     if [ "$remote_ref" = "refs/heads/dev" || "$remote_ref" = "refs/heads/stage" || "$remote_ref" = "refs/heads/prod"  ]; then
        echo "Pushing to branch dev ,stage or prod is forbidden"
        exit 1
     fi
done

exit 0
